fix: support jest 27
testing-library/angular-testing-library pull request #233
Opened 2021-07-02 06:33 UTC by timdeschryver

2021-07-02 06:41 UTC, nickmccurdy requested changes
I'm not familiar with the codebase, but the code looks good to me, and the upgrades seem to be working properly. Thanks for your help.

I think it would still be a good idea to remove the `jest/no-done-callback` ESLint rule from the config before merging, as Jest 27 requires you to either use `done` or `async/await`, and only using `async/await` would be more consistent and modern.

2021-07-02 06:43 UTC, timdeschryver commented
👍 I'm currently taking a look at the PR that you've created.
I'm going to copy over some changes:

-  `jest/no-done-callback`
- jest config
- maybe more :)

2021-07-04 12:07 UTC, nickmccurdy approved these changes

2021-07-04 13:45 UTC, merged

2021-07-04 13:45 UTC, timdeschryver commented
Thanks @nickmccurdy